[profile.mega]
inherits = "release"
codegen-units = 1
lto = true
strip = true

[alias]
mega = "build --profile mega --config build.rustflags=[\"-Ctarget-cpu=native\",\"-Cprefer-dynamic=no\"]"
m = "mega"
