import = [
  "~/.config/alacritty/colors.toml",
  "~/.config/alacritty/font.toml",
  "~/.config/alacritty/options.toml",
  "~/.config/alacritty/system.toml",
  "~/.config/alacritty/transient.toml",
]

[keyboard]
bindings = [
  { key = "Return", mods = "Super",   action = "ToggleFullscreen" },
  { key = "N",      mods = "Super",   action = "CreateNewWindow"  },
  { key = "Q",      mods = "Control", chars = "\u0011" },
  { key = "Left",   mods = "Alt",     chars = "\u001Bb" },
  { key = "Right",  mods = "Alt",     chars = "\u001Bf" },
  { key = "Z",      mods = "Super",   command = { program = "zsh", args = ["-c", "~/.config/alacritty/toggle_font.sh"] } },
]
