font:
  normal:
    family: DejaVuSansM Nerd Font Mono

key_bindings:
  - { key: N, mods: Super,       action: CreateNewWindow }

shell:
  program: zsh
  args:
    - -l
    - -c
    - TERM=alacritty-direct tmux
