#!/usr/bin/env bash
if cat /etc/shells | grep zsh &> /dev/null
then
  shell=zsh
else
  shell=bash
fi

if tmux list-sessions 2> /dev/null | grep main: > /dev/null
then
  if [ $(tmux list-sessions | wc -l) == 1 ]
  then
    while true
    do
      tput -Txterm reset
      echo -e "[31mOnly main session exists[m"
      echo "What do you whish to do?"
      echo -e "[[33mA[m]ttach to main"
      echo -e "[[33mN[m]ame new session"
      echo -e "[[33mE[m]xit?"
      read -p "Choice: " input
      case $input in
        [Aa]* )
          tmux attach -t main
          tput -Txterm reset
          exit
          ;;
        [Nn]* )
          echo -e "Current sessions:[32m"
          tmux list-sessions
          echo -e -n "[m"
          read -p "Name of the session: " name
          if tmux new-session -s $name
          then
            tput -Txterm reset
            exit
          else
            echo -e "[31mUnable to create[m"
          fi
          ;;
        [Ee]* )
          tput -Txterm reset
          exit
          ;;
      esac
    done
  else
    while true
    do
      tput -Txterm reset
      echo -e "[31mSeveral sessions found[m"
      echo "What do you whish to do?"
      echo -e "[[33mC[m]onnect to main"
      echo -e "[[33mN[m]ame new session"
      echo -e "[[33mA[m]ttach to last"
      echo -e "[[33mP[m]ick session"
      echo -e "[[33mL[m]og normally"
      echo -e "[[33mE[m]xit?"
      read -p "Choice: " input

      case $input in
        [Cc]* )
          tmux attach -t main
          tput -Txterm reset
          exit
          ;;
        [Nn]* )
          echo -e "Current sessions:[32m"
          tmux list-sessions
          echo -e -n "[m"
          read -p "Name of the session: " name
          if tmux new-session -s $name
          then
            tput -Txterm reset
            exit
          else
            echo -e "[31mUnable to create[m"
          fi
          ;;
        [Aa]* )
          # First line
          name=$(tmux list-sessions | head -1 | cut -f1 -d ":")
          # Last line
          #name=$(tmux list-sessions | sed -e '$!d' | cut -f1 -d ":")
          if tmux attach -t $name
          then
            tput -Txterm reset
            exit
          else
            echo -e "[31mUnable to attach[m"
          fi
          ;;
        [Pp]* )
          echo -e "Current sessions:[32m"
          tmux list-sessions
          echo -e -n "[m"
          read -p "Name of the session: " name
          if tmux attach -t $name
          then
            tput -Txterm reset
            exit
          else
            echo -e "[31mUnable to attach[m"
          fi
          ;;
        [Ll]* )
          $($shell)
          exit
          ;;
        [Ee]* )
          tput -Txterm reset
          exit
          ;;
      esac
    done
  fi	
else
  if tmux list-sessions &> /dev/null
  then
    while true
    do
      tput -Txterm reset
      echo -e "[31mMain session not found[m"
      echo "What do you whish to do?"
      echo -e "[[33mC[m]reate main"
      echo -e "[[33mN[m]ame new session"
      echo -e "[[33mA[m]ttach to last"
      echo -e "[[33mP[m]ick session"
      echo -e "[[33mL[m]og normally"
      echo -e "[[33mE[m]xit?"
      read -p "Choice: " input

      case $input in
        [Cc]* )
          tmux new-session -s main
          tput -Txterm reset
          exit
          ;;
        [Nn]* )
          echo -e "Current sessions:[32m"
          tmux list-sessions
          echo -e -n "[m"
          read -p "Name of the session: " name
          if tmux new-session -s $name
          then
            tput -Txterm reset
            exit
          else
            echo -e "[31mUnable to create[m"
          fi
          ;;
        [Aa]* )
          # First line
          name=$(tmux list-sessions | head -1 | cut -f1 -d ":")
          # Last line
          #name=$(tmux list-sessions | sed -e '$!d' | cut -f1 -d ":")
          if tmux attach -t $name
          then
            tput -Txterm reset
            exit
          else
            echo -e "[31mUnable to attach[m"
          fi
          ;;
        [Pp]* )
          echo -e "Current sessions:[32m"
          tmux list-sessions
          echo -e -n "[m"
          read -p "Name of the session: " name
          if tmux attach -t $name
          then
            tput -Txterm reset
            exit
          else
            echo -e "[31mUnable to attach[m"
          fi
          ;;
        [Ll]* )
          /usr/bin/env $shell
          exit
          ;;
        [Ee]* )
          tput -Txterm reset
          exit
          ;;
      esac
    done
  else
    while true
    do
      tput -Txterm reset
      echo -e "[31mNo sessions found[m"
      echo "What do you whish to do?"
      echo -e "[[33mC[m]reate main"
      echo -e "[[33mN[m]ame new session"
      echo -e "[[33mL[m]og normally"
      echo -e "[[33mE[m]xit?"
      read -p "Choice: " input

      case $input in
        [Cc]* )
          tmux new-session -s main
          tput -Txterm reset
          exit
          ;;
        [Nn]* )
          read -p "Name of the session: " name
          if tmux new-session -s $name
          then
            tput -Txterm reset
            exit
          else
            echo -e "[31mUnable to create[m"
          fi
          ;;
        [Ll]* )
          /usr/bin/env $shell
          tput -Txterm reset
          exit
          ;;
        [Ee]* )
          tput -Txterm reset
          exit
          ;;
      esac
    done
  fi
fi
