#!/usr/bin/env bash

if which cargo-hack > /dev/null; then
  hack=1
fi

shift

while (( $# > 0 )); do
  case "${1}" in
    nightly)
      nightly='+nightly' ;;
    run|r)
      run=1 ;;
    skip|s)
      shift
      if [[ "${hack}" ]]; then
        skip="--skip ${1}"
      else
        echo "[33mCould not find 'cargo-hack'. Ignoring the 'skip' parameter[m"
      fi
      ;;
    clean|c)
      clean=1 ;;
  esac
  shift
done

if [ ${clean} ]; then
  echo "[34mCleaning[m" && \
  cargo clean
fi && \
echo "[34mFormatting[m" && \
cargo ${nightly} fmt --all && \
if which cargo-hack > /dev/null; then
  echo "[34mChecking main[m" && \
  cargo ${nightly} hack --feature-powerset ${skip} check --workspace ${@} && \
  echo "[34mChecking examples[m" && \
  cargo ${nightly} hack --feature-powerset ${skip} check --workspace --examples ${@} && \
  echo "[34mChecking tests[m" && \
  cargo ${nightly} hack --feature-powerset ${skip} check --workspace --tests ${@} && \
  echo "[34mLinting main[m" && \
  cargo ${nightly} hack --feature-powerset ${skip} clippy --workspace ${@} && \
  echo "[34mLinting tests[m" && \
  cargo ${nightly} hack --feature-powerset ${skip} clippy --workspace --tests ${@} && \
  echo "[34mLinting examples[m" && \
  cargo ${nightly} hack --feature-powerset ${skip} clippy --workspace --examples ${@} && \
  echo "[34mTesting main[m" && \
  cargo ${nightly} hack --feature-powerset ${skip} test --workspace ${@}
else
  echo "[33mNot running feature powerset[m" && \
  echo "[34mChecking main[m" && \
  cargo ${nightly} check --workspace ${@} && \
  echo "[34mChecking examples[m" && \
  cargo ${nightly} check --workspace --examples ${@} && \
  echo "[34mChecking examples[m" && \
  cargo ${nightly} check --workspace --tests ${@} && \
  echo "[34mLinting main[m" && \
  cargo ${nightly} clippy --workspace ${@} && \
  echo "[34mLinting tests[m" && \
  cargo ${nightly} clippy --workspace --tests ${@} && \
  echo "[34mLinting examples[m" && \
  cargo ${nightly} clippy --workspace --examples ${@} && \
  echo "[34mTesting main[m" && \
  cargo ${nightly} test --workspace ${@}
fi && \
if [ "${run}" ]; then
  echo "[34mRunning[m" && \
  cargo ${nightly} run ${@}
fi
