#!/bin/bash

shift

if [[ "${1}" == "nightly" ]]; then
  nightly='+nightly'
  shift
fi

if [[ "${1}" == "--run" ]]; then
  run=1
  shift
fi

echo "[34mFormatting[m" && \
cargo ${nightly} fmt --all && \
echo "[34mBuilding main[m" && \
cargo ${nightly} build --workspace --all-features ${@} && \
echo "[34mBuilding targets[m" && \
cargo ${nightly} build --workspace --all-targets ${@} && \
echo "[34mBuilding examples[m" && \
cargo ${nightly} build --workspace --examples ${@} && \
echo "[34mLinting main[m" && \
cargo ${nightly} clippy --workspace --all-features ${@} && \
echo "[34mLinting targets[m" && \
cargo ${nightly} clippy --workspace --all-targets ${@} && \
echo "[34mLinting examples[m" && \
cargo ${nightly} clippy --workspace --examples ${@} && \
echo "[34mTesting main[m" && \
cargo ${nightly} test --workspace --all-features ${@} && \
echo "[34mTesting targets[m" && \
cargo ${nightly} test --workspace --all-targets ${@}
if [ "${run}" ]; then
  echo "[34mRunning[m" && \
  cargo ${nightly} run ${@}
fi
