#!/bin/bash

# A crude (vry crude) halper for wasm-bindgen applications

if ! command -v wasm-bindgen; then
  echo "[34mCould not find wasm-bindgen[m" >&2
  echo "Downloand it from https://github.com/rustwasm/wasm-bindgen/releases" >&2
  exit -1
fi

workspace_dir=`cargo metadata --format-version 1 | jq -r '.workspace_root'`
base_dir=`cargo locate-project | jq -r '.root' | xargs dirname`

shift

if [[ "${1}" == "wasi" ]]
then
  target='wasm32-wasi'
  shift
else
  target='wasm32-unknown-unknown'
fi

echo 'Building target "'${target}'" in release mode'
if ! cargo build --target ${target} --release --lib
then
  exit -1
fi

output=`ls "${workspace_dir}"/target/${target}/release/*.wasm | head -1 | xargs basename | cut -d'.' -f1`

if ! wasm-bindgen "${workspace_dir}/target/${target}/release/${output}.wasm" --out-dir "${base_dir}/static" --web
then
  exit -1
fi

if [ -f "${base_dir}/index.html" ]
then
  cp "${base_dir}/index.html" "${base_dir}/static/index.html"
else
  echo '<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8"/>
    <title>'"${output}"'</title>
  </head>
  <body>
    <script type="module">
      import init from "./'"${output}"'.js";

      init("./'"${output}"'_bg.wasm");
    </script>
  </body>
</html>' > "${base_dir}/static/index.html"
fi

if [[ "${1}" == "--run" ]]; then
  simple-server "${base_dir}/static"
fi
