#!/usr/bin/env bash

INTERVAL="1"  # update interval in seconds

if [ -z "$1" ]
then
  echo
  echo usage: $0 [network-interface]
  echo
  echo e.g. $0 eth0
  echo
  echo shows packets-per-second
  exit -1
fi

if [ ! -d /sys/class/net/$1 ]
then
  echo Invalid network interface
  exit -1
fi

IF=$1

while true
do
  R1=`cat /sys/class/net/$1/statistics/rx_packets`
  T1=`cat /sys/class/net/$1/statistics/tx_packets`
  sleep $INTERVAL
  R2=`cat /sys/class/net/$1/statistics/rx_packets`
  T2=`cat /sys/class/net/$1/statistics/tx_packets`
  TXPPS=`expr $T2 - $T1`
  RXPPS=`expr $R2 - $R1`
  echo -ne "TX $1: $TXPPS pkts/s RX $1: $RXPPS pkts/s        "\\r
done
