export COMPUTER_SYMBOL='§'
# export COMPUTER_SYMBOL='φ'
# export COMPUTER_SYMBOL='π'
# export COMPUTER_SYMBOL='Њ'
# export COMPUTER_SYMBOL='☧'
# export COMPUTER_SYMBOL='ɳ'
# export COMPUTER_SYMBOL='✝'
# export COMPUTER_SYMBOL='#'
# export COMPUTER_SYMBOL='☢'
# export COMPUTER_SYMBOL='ø'
# export COMPUTER_SYMBOL='ƛ'
# export COMPUTER_SYMBOL='τ'
# export COMPUTER_SYMBOL='⏾'
# export COMPUTER_SYMBOL=''

# alias pc='pacaur --color always'
# alias pcm='pacman --color always'
